### ISSUE TITLE
1.8: docs/ directory is not included in dist tar ball

### ISSUE THREAD

**Issue by kloczek** [rhinstaller/python-simpleline#102]
Yeah looks like documentation is missing in dist tar ball.
You are not keeping .po files in git repo so it cannot be used as well autogenerated from git tag tar ball.
It would be good to add `docs/` do dist tar ball or add .po filess to git repo.
If one of those thow thing woiuld be done is it possible to add it an make new release (1.8.1?) .. please

If you would choose to add .po files to git repo IMO it would be nice to change tagging convention from current `simpleline-<version>` to just `<version>` because github/gitlab automatically uses `<repo_name>-<tag>/` as base direcotory in autogenerated tar ball.
You can see that in https://github.com/rhinstaller/python-simpleline/archive/refs/tags/simpleline-1.8.tar.gz

**Comment by jkonecny12** [comment]
Thanks for pointing that out. I will take a look on that.

**Comment by jkonecny12** [comment]
Everything should be resolved now. I'll do a new release on Monday.
